using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Npgsql;
using StatsHub.Api.Data;

namespace StatsHub.Api.Tests;

// The one-time move from numeric ids to UUIDs, on a database built the old
// way: numeric ids, a family's worth of rows, and the awkward cases - a
// manual and a synced game whose home team share the old number 2 (an app
// Team for one, an IbbaTeam for the other), a game pointing at a team that
// was deleted, and a table left over from an older version.
public abstract class UuidMigrationTestsBase
{
    protected abstract bool Postgres { get; }
    protected abstract AppDbContext NewContext();

    private void Execute(AppDbContext db, string sql, Dictionary<string, object?>? parameters = null)
    {
        var connection = db.Database.GetDbConnection();
        if (connection.State != System.Data.ConnectionState.Open) connection.Open();
        using var command = connection.CreateCommand();
        command.CommandText = sql;
        foreach (var (name, value) in parameters ?? new())
        {
            var parameter = command.CreateParameter();
            parameter.ParameterName = name;
            parameter.Value = value ?? DBNull.Value;
            command.Parameters.Add(parameter);
        }
        command.ExecuteNonQuery();
    }

    // The schema as it was: the current model with every UUID column numeric.
    private void CreateLegacySchema(AppDbContext db)
    {
        foreach (var table in UuidMigration.TableOrder)
        {
            var entity = db.Model.GetEntityTypes().Single(e => e.GetTableName() == table);
            var columns = new List<string>();
            foreach (var property in entity.GetProperties())
            {
                var name = property.GetColumnName();
                if (name == "Id")
                {
                    columns.Add(Postgres ? "\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" : "\"Id\" INTEGER PRIMARY KEY AUTOINCREMENT");
                    continue;
                }
                var isId = property.ClrType == typeof(Guid) || property.ClrType == typeof(Guid?);
                var type = isId ? (Postgres ? "integer" : "INTEGER") : property.GetColumnType();
                columns.Add($"\"{name}\" {type}{(property.IsNullable ? "" : " NOT NULL")}");
            }
            foreach (var fk in entity.GetForeignKeys())
                columns.Add($"FOREIGN KEY (\"{fk.Properties[0].GetColumnName()}\") REFERENCES \"{fk.PrincipalEntityType.GetTableName()}\" (\"Id\") ON DELETE CASCADE");
            Execute(db, $"CREATE TABLE \"{table}\" ({string.Join(", ", columns)})");
        }
        // A table from an older version, still pointing at a current one.
        Execute(db, "CREATE TABLE \"IbbaTeamLinks\" (\"Id\" integer PRIMARY KEY, \"PlayerIbbaLinkId\" integer NOT NULL REFERENCES \"PlayerIbbaLinks\" (\"Id\") ON DELETE CASCADE)");
    }

    // One old-style row; required columns not given get an empty value.
    private void Insert(AppDbContext db, string table, object values)
    {
        var given = values.GetType().GetProperties().ToDictionary(p => p.Name, p => p.GetValue(values));
        var entity = db.Model.GetEntityTypes().Single(e => e.GetTableName() == table);
        foreach (var property in entity.GetProperties())
        {
            var name = property.GetColumnName();
            if (given.ContainsKey(name) || property.IsNullable) continue;
            var type = Nullable.GetUnderlyingType(property.ClrType) ?? property.ClrType;
            given[name] = type == typeof(string) ? "" : type == typeof(bool) ? false : type == typeof(DateTime) ? DateTime.UtcNow
                : type == typeof(double) ? 0.0 : type == typeof(decimal) ? 0m : type == typeof(long) ? 0L : 0;
        }
        var names = given.Keys.ToList();
        Execute(db,
            $"INSERT INTO \"{table}\" ({string.Join(", ", names.Select(n => $"\"{n}\""))}) VALUES ({string.Join(", ", names.Select((_, i) => $"@p{i}"))})",
            names.Select((n, i) => (n, i)).ToDictionary(x => $"@p{x.i}", x => given[x.n]));
    }

    private void SeedLegacyFamily(AppDbContext db)
    {
        Insert(db, "Users", new { Id = 1, Email = "mom@test.local", FirstName = "Mom" });
        Insert(db, "Users", new { Id = 2, Email = "dad@test.local", FirstName = "Dad" });
        Insert(db, "Users", new { Id = 3, Email = "idan@test.local", FirstName = "Idan", Role = "Player" });
        Insert(db, "IbbaTeams", new { Id = 1, Name = "Maccabi", IbbaTeamId = "t1", TeamUrl = "https://example.test/1", LeagueUrl = "https://example.test/l", LeagueName = "U16" });
        Insert(db, "IbbaTeams", new { Id = 2, Name = "Hapoel", IbbaTeamId = "t2", TeamUrl = "https://example.test/2", LeagueUrl = "https://example.test/l", LeagueName = "U16" });
        Insert(db, "Players", new { Id = 1, UserId = 1, LinkedUserId = (int?)3, FirstName = "Idan" });
        Insert(db, "Players", new { Id = 2, UserId = 1, FirstName = "Neri" });
        Insert(db, "PlayerParents", new { Id = 1, PlayerId = 1, UserId = 1 });
        Insert(db, "PlayerParents", new { Id = 2, PlayerId = 1, UserId = 2 });
        Insert(db, "PlayerParents", new { Id = 3, PlayerId = 2, UserId = 1 });
        Insert(db, "Seasons", new { Id = 1, UserId = 1, Name = "2026" });
        Insert(db, "Teams", new { Id = 1, SeasonId = 1, Name = "Maccabi U16", IbbaTeamId = (int?)1 });
        Insert(db, "Teams", new { Id = 2, SeasonId = 1, Name = "School team" });
        Insert(db, "PlayerTeams", new { Id = 1, PlayerId = 1, TeamId = 1 });
        Insert(db, "PlayerTeams", new { Id = 2, PlayerId = 2, TeamId = 2 });
        // Manual game: home 2 = the app Team "School team".
        Insert(db, "Games", new { Id = 1, OpponentName = "Manual opponent", HomeTeamId = (int?)2, LiveTrackedByUserId = (int?)2, GameType = "League", Status = "Completed" });
        // Synced game: home 1 / away 2 = IbbaTeams Maccabi / Hapoel.
        Insert(db, "Games", new { Id = 2, OpponentName = "", IbbaGameCode = "G-2", HomeTeamId = (int?)1, AwayTeamId = (int?)2, GameType = "League", Status = "Completed" });
        // Manual game whose team was deleted long ago.
        Insert(db, "Games", new { Id = 3, OpponentName = "Orphan", HomeTeamId = (int?)99, GameType = "Friendly", Status = "Completed" });
        Insert(db, "GameStats", new { Id = 1, GameId = 1, PlayerId = 2, Assists = 3 });
        Insert(db, "GameStats", new { Id = 2, GameId = 2, PlayerId = 1, Assists = 7 });
        Insert(db, "Shots", new { Id = 1, GameStatsId = 2, Made = true });
        Insert(db, "Shots", new { Id = 2, GameStatsId = 2, Made = false });
        Insert(db, "ShareLinks", new { Id = 1, PlayerId = 1, GameId = (int?)2, CreatedByUserId = 1, Token = "share-token" });
        Insert(db, "PlayerIbbaLinks", new { Id = 1, PlayerId = 1, IbbaPlayerUrl = "https://example.test/p/1" });
        Insert(db, "PlayerIbbaTeams", new { Id = 1, PlayerIbbaLinkId = 1, IbbaTeamId = 1 });
        Insert(db, "PushSubscriptions", new { Id = 1, UserId = 2, Endpoint = "https://push.example.test/1", P256dh = "k", Auth = "a" });
        Execute(db, "INSERT INTO \"IbbaTeamLinks\" (\"Id\", \"PlayerIbbaLinkId\") VALUES (1, 1)");
    }

    protected void ConvertsAnOldDatabaseKeepingEveryLink()
    {
        using (var legacy = NewContext())
        {
            CreateLegacySchema(legacy);
            SeedLegacyFamily(legacy);
            Assert.True(UuidMigration.IsLegacy(legacy));
            UuidMigration.Run(legacy, NullLogger.Instance);
        }

        using var db = NewContext();
        Assert.False(UuidMigration.IsLegacy(db));

        if (Postgres)
        {
            // The original tables are kept, untouched, as a copy to go back to.
            var connection = db.Database.GetDbConnection();
            connection.Open();
            using var command = connection.CreateCommand();
            command.CommandText = $"SELECT string_agg(\"Email\", ',' ORDER BY \"Id\") FROM \"{UuidMigration.BackupSchema}\".\"Users\"";
            Assert.Equal("mom@test.local,dad@test.local,idan@test.local", command.ExecuteScalar());
            command.CommandText = $"SELECT count(*) FROM \"{UuidMigration.BackupSchema}\".\"Shots\"";
            Assert.Equal(2L, command.ExecuteScalar());
            connection.Close();
        }

        var users = db.Users.OrderBy(u => u.Id).ToList();
        Assert.Equal(["mom@test.local", "dad@test.local", "idan@test.local"], users.Select(u => u.Email)); // old order kept
        var (mom, dad, idanUser) = (users[0], users[1], users[2]);

        var idan = db.Players.Include(p => p.Parents).Single(p => p.FirstName == "Idan");
        Assert.Equal(mom.Id, idan.UserId);
        Assert.Equal(idanUser.Id, idan.LinkedUserId);
        Assert.Equal(new[] { mom.Id, dad.Id }.Order(), idan.Parents.Select(pp => pp.UserId).Order());

        var maccabi = db.IbbaTeams.Single(t => t.Name == "Maccabi");
        var hapoel = db.IbbaTeams.Single(t => t.Name == "Hapoel");
        var schoolTeam = db.Teams.Single(t => t.Name == "School team");
        Assert.Equal(maccabi.Id, db.Teams.Single(t => t.Name == "Maccabi U16").IbbaTeamId);
        Assert.Equal(db.Seasons.Single().Id, schoolTeam.SeasonId);
        Assert.Contains(db.PlayerTeams.ToList(), pt => pt.PlayerId == idan.Id && pt.TeamId == db.Teams.Single(t => t.Name == "Maccabi U16").Id);

        var manual = db.Games.Single(g => g.OpponentName == "Manual opponent");
        Assert.Equal(schoolTeam.Id, manual.HomeTeamId);         // an app Team...
        Assert.Equal(dad.Id, manual.LiveTrackedByUserId);
        var synced = db.Games.Single(g => g.IbbaGameCode == "G-2");
        Assert.Equal(maccabi.Id, synced.HomeTeamId);            // ...vs IbbaTeams for the same old numbers
        Assert.Equal(hapoel.Id, synced.AwayTeamId);
        Assert.Null(db.Games.Single(g => g.OpponentName == "Orphan").HomeTeamId);

        var stats = db.GameStats.Include(gs => gs.Shots).Single(gs => gs.Assists == 7);
        Assert.Equal(synced.Id, stats.GameId);
        Assert.Equal(idan.Id, stats.PlayerId);
        Assert.Equal(2, stats.Shots.Count);
        Assert.Equal(manual.Id, db.GameStats.Single(gs => gs.Assists == 3).GameId);

        var share = db.ShareLinks.Single(s => s.Token == "share-token");
        Assert.Equal((idan.Id, synced.Id, mom.Id), (share.PlayerId, share.GameId!.Value, share.CreatedByUserId));
        var link = db.PlayerIbbaLinks.Include(l => l.Teams).Single();
        Assert.Equal(idan.Id, link.PlayerId);
        Assert.Equal(maccabi.Id, link.Teams.Single().IbbaTeamId);
        Assert.Equal(dad.Id, db.PushSubscriptions.Single().UserId);

        // New rows work alongside the converted ones.
        db.Players.Add(new Models.Player { UserId = mom.Id, FirstName = "New", LastName = "Kid" });
        db.SaveChanges();
        Assert.Equal(3, db.Players.Count());
    }
}

public sealed class SqliteUuidMigrationTests : UuidMigrationTestsBase, IDisposable
{
    private readonly string _path = Path.Combine(Path.GetTempPath(), $"statshub-legacy-{Guid.NewGuid():N}.db");
    protected override bool Postgres => false;
    protected override AppDbContext NewContext() => new(new DbContextOptionsBuilder<AppDbContext>().UseSqlite($"Data Source={_path}").Options);

    [Fact]
    public void Converts_an_old_database_keeping_every_link() => ConvertsAnOldDatabaseKeepingEveryLink();

    public void Dispose()
    {
        SqliteConnection.ClearAllPools();
        foreach (var file in Directory.GetFiles(Path.GetDirectoryName(_path)!, Path.GetFileNameWithoutExtension(_path) + "*"))
            File.Delete(file); // the database and its pre-conversion backup
    }
}

// Production runs Postgres. Runs where a server is given in
// STATSHUB_TEST_POSTGRES (the CI workflow starts one); skipped elsewhere.
public sealed class PostgresUuidMigrationTests : UuidMigrationTestsBase, IDisposable
{
    private static readonly string? Server = Environment.GetEnvironmentVariable("STATSHUB_TEST_POSTGRES");
    private readonly string _database = $"statshub_legacy_{Guid.NewGuid():N}";
    protected override bool Postgres => true;

    public PostgresUuidMigrationTests()
    {
        if (Server == null) return;
        using var admin = new NpgsqlConnection(Server);
        admin.Open();
        using var command = new NpgsqlCommand($"CREATE DATABASE \"{_database}\"", admin);
        command.ExecuteNonQuery();
    }

    protected override AppDbContext NewContext() =>
        new(new DbContextOptionsBuilder<AppDbContext>().UseNpgsql(new NpgsqlConnectionStringBuilder(Server) { Database = _database }.ConnectionString).Options);

    [PostgresFact]
    public void Converts_an_old_database_keeping_every_link() => ConvertsAnOldDatabaseKeepingEveryLink();

    public void Dispose()
    {
        if (Server == null) return;
        NpgsqlConnection.ClearAllPools();
        using var admin = new NpgsqlConnection(Server);
        admin.Open();
        using var command = new NpgsqlCommand($"DROP DATABASE IF EXISTS \"{_database}\" WITH (FORCE)", admin);
        command.ExecuteNonQuery();
    }
}

public sealed class PostgresFactAttribute : FactAttribute
{
    public PostgresFactAttribute()
    {
        if (Environment.GetEnvironmentVariable("STATSHUB_TEST_POSTGRES") == null)
            Skip = "No Postgres server (set STATSHUB_TEST_POSTGRES) - runs in CI.";
    }
}
